# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ec2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test EC2 Suites
      run: go test -v ./ec2/...

    - name: Build EC2 Main.go
      run: go build -v ./ec2/...
  build-private-lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test Private Lambda Suites
      run: go test -v ./lambda/private/...

    - name: Build Private Lambda Main.go
      run: go build -v ./lambda/private/...
  build-public-lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test Public Lambda Suites
      run: go test -v ./lambda/public/...

    - name: Build Public Lambda Main.go
      run: go build -v ./lambda/public/...
